### ISSUE TITLE
Download von File bringt HTML-Seite

### ISSUE THREAD

**Issue by Fanello** [FriendsOfREDAXO/be_explorer#7]
Wenn ich im Backend-Explorer z.B. auf assets > css gehe und bei meinem CSS-Style (z.B. style.css) ganz rechts auf das Download-Symbol klicke, kann ich das File downloaden.
Allerdings zeigt es mir als Inhalt nicht das CSS, sondern das Redaxo-Backend als HTML. Und zwar bis zu dieser Zeil, danach bricht es ab:
`<script type="text/javascript" src="../assets/addons/ckeditor/vendor/ckeditor.js?buster=1584438753`

**Comment by pschuchmann** [comment]
@Fanello habe es eben nachstellen können, sehe ich mir bei Gelegenheit an! Wollte das Addon grundsätzlich überarbeiten, vielleicht passiert es auch erst in dem Zug. Danke dir fürs Melden!
