### ISSUE TITLE
AddOn archivieren?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/be_explorer#9]
@pschuchmann 
@rkemmere

**Comment by pschuchmann** [comment]
Wegen mir ja, glaube das Security Problem ist ja immer noch nicht so richtig gelöst.

**Comment by rkemmere** [comment]
Welches Security Problem ist es denn genau? Laut dem Git vom tinyfilemanager sind einige Issues behoben.

**Comment by rkemmere** [comment]
Ich habe eben mal die vendor bei uns getauscht und die läuft.

**Comment by skerbis** [comment]
https://github.com/prasathmani/tinyfilemanager/issues/273 schlägt immer noch an

**Comment by rkemmere** [comment]
Wo kann man das mal testen? Bei dem Großteil der deutschen Hoster läuft das Addon. (All-Inkl., DF, 1und1, Strato, Vistec)

**Comment by skerbis** [comment]
Bei einigen Hostern ist ImunifyAV mit installiert. Auch auf meinen Servern ist dies der Fall. Meist als Paket bei PLESK Servern. 
Das AddOn ICECoder ist zudem ein guter Ersatz.

**Comment by skerbis** [comment]
ich close dann mal und archiviere das Repo hier. 
Wer wer sich der Sache annehmen möchte kann die Archivierung ja wieder auflösen.
